#!/bin/bash
### BEGIN INIT INFO
#
# Provides: ninja
# Required-Start: $remote_fs $syslog 
# Required-Stop: $remote_fs $syslog 
# Default-Start: 2 3 4 5 
# Default-Stop: 0 1 6
# Short desciption: Superbowl Ninja Web Application
# Description: Web based administration of timber bowl production process
#
### END INIT INFO
#
# chkconfig: 345 20 80
# description: Ninja start/shutdown script
# processname: java
#
# Installation:
# copy file to /etc/init.d
# chmod +x /etc/init.d/ninja

# chkconfig --add /etc/init.d/ninja
# chkconfig ninja on
#     OR on a Debian system
# sudo update-rc.d ninja defaults
#
#
# Usage: (as root)
# service ninja start
# service ninja stop
# service ninja status
# service ninja restart
# service ninja clean
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Path to the application
APPLICATION_NAME=superbowl
APPLICATION_PATH=/srv/ninja_applications/${APPLICATION_NAME}/bin
APPLICATION_JAR=superbowl.jar

PID_FILE=/var/run/${APPLICATION_NAME}.pid
PORT=9000

# Path to the JVM
JAVA_BIN=/usr/lib/jvm/java-8-openjdk-i386/bin/java
PARAMS="-Dninja.port=${PORT} -jar ${APPLICATION_PATH}/${APPLICATION_JAR}"

# User running the Ninja process
USER=ninja

RETVAL=0

start() {
    if [ -f ${PID_FILE} ]; then
        echo "Ninja application ${APPLICATION_NAME} already running"
    else
        echo -n "Starting Ninja Application: ${APPLICATION_NAME}"
        DAEMON_START_LINE="start-stop-daemon --chdir=${APPLICATION_PATH} --make-pidfile --pidfile ${PID_FILE} --chuid ${USER} --exec ${JAVA_BIN} --background --start -- ${PARAMS}"
        ${DAEMON_START_LINE}
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            echo " - Success"
        else
            echo " - Failure"
        fi
        #echo
    fi
    #echo

}
stop() {
    echo -n "Stopping Ninja application: ${APPLICATION_NAME}"
    kill -9 `cat ${PID_FILE}`
    RETVAL=$?
    rm -rf ${PID_FILE}
    if [ $RETVAL -eq 0 ]; then
        echo " - Success"
    else
        echo " - Failure"
    fi
        #echo
    }

status() {
    echo -n "Status information of Ninja application ${APPLICATION_NAME}"
    if [ -f ${PID_FILE} ]; then
        echo "Ninja application ${APPLICATION_NAME} running"
    else
        echo "Ninja application ${APPLICATION_NAME} not running"
    fi
    #echo

}

clean() {
    echo -n "Removing Superbowl PID file: ${PID_FILE}"
    rm -f ${PID_FILE}
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart|reload)
    stop
    sleep 10
    start
    ;;
    status)
    status
    ;;
    clean)
    clean
    ;;
*)
echo "Usage: $0 {start|stop|restart|status|clean}"
esac


